apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: workshop-nginx-deployment-<your-name>
spec:
  selector:
    matchLabels:
      app: workshop-nginx-<your-name>
  replicas: 3
  template:
    metadata:
      labels:
        app: workshop-nginx-<your-name>
    spec:
      containers:
      - name: nginx
        image: nginxdemos/hello
        ports:
        - containerPort: 80
        volumeMounts:
          - name: config-volume
            mountPath: /usr/share/nginx/html/
      volumes:
      - name: config-volume
        configMap:
          name: workshop-config-<your-name>